config/routes.rb
Rails.application.routes.draw do
  get 'pagina/home'
	root 'pagina#home'

  resources :atletas
  resources :modalidades
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atleta.rb
class Atleta < ApplicationRecord
  belongs_to :modalidade
	
	mount_uploader :photo, PhotoAtletaUploader
end

app/models/modalidade.rb
class Modalidade < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/atletas_controller.rb
class AtletasController < ApplicationController
  before_action :set_atleta, only: [:show, :edit, :update, :destroy]

  # GET /atletas
  # GET /atletas.json
  def index
    @atletas = Atleta.all
  end

  # GET /atletas/1
  # GET /atletas/1.json
  def show
  end

  # GET /atletas/new
  def new
    @atleta = Atleta.new
  end

  # GET /atletas/1/edit
  def edit
  end

  # POST /atletas
  # POST /atletas.json
  def create
    @atleta = Atleta.new(atleta_params)

    respond_to do |format|
      if @atleta.save
        format.html { redirect_to @atleta, notice: 'Atleta was successfully created.' }
        format.json { render :show, status: :created, location: @atleta }
      else
        format.html { render :new }
        format.json { render json: @atleta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atletas/1
  # PATCH/PUT /atletas/1.json
  def update
    respond_to do |format|
      if @atleta.update(atleta_params)
        format.html { redirect_to @atleta, notice: 'Atleta was successfully updated.' }
        format.json { render :show, status: :ok, location: @atleta }
      else
        format.html { render :edit }
        format.json { render json: @atleta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atletas/1
  # DELETE /atletas/1.json
  def destroy
    @atleta.destroy
    respond_to do |format|
      format.html { redirect_to atletas_url, notice: 'Atleta was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atleta
      @atleta = Atleta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atleta_params
      params.require(:atleta).permit(:nome, :photo, :descricao, :modalidade_id)
    end
end

app/controllers/modalidades_controller.rb
class ModalidadesController < ApplicationController
  before_action :set_modalidade, only: [:show, :edit, :update, :destroy]

  # GET /modalidades
  # GET /modalidades.json
  def index
    @modalidades = Modalidade.all
  end

  # GET /modalidades/1
  # GET /modalidades/1.json
  def show
  end

  # GET /modalidades/new
  def new
    @modalidade = Modalidade.new
  end

  # GET /modalidades/1/edit
  def edit
  end

  # POST /modalidades
  # POST /modalidades.json
  def create
    @modalidade = Modalidade.new(modalidade_params)

    respond_to do |format|
      if @modalidade.save
        format.html { redirect_to @modalidade, notice: 'Modalidade was successfully created.' }
        format.json { render :show, status: :created, location: @modalidade }
      else
        format.html { render :new }
        format.json { render json: @modalidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modalidades/1
  # PATCH/PUT /modalidades/1.json
  def update
    respond_to do |format|
      if @modalidade.update(modalidade_params)
        format.html { redirect_to @modalidade, notice: 'Modalidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @modalidade }
      else
        format.html { render :edit }
        format.json { render json: @modalidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modalidades/1
  # DELETE /modalidades/1.json
  def destroy
    @modalidade.destroy
    respond_to do |format|
      format.html { redirect_to modalidades_url, notice: 'Modalidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modalidade
      @modalidade = Modalidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def modalidade_params
      params.require(:modalidade).permit(:nome, :descricao)
    end
end

app/controllers/pagina_controller.rb
class PaginaController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atletas_helper.rb
module AtletasHelper
end

app/helpers/modalidades_helper.rb
module ModalidadesHelper
end

app/helpers/pagina_helper.rb
module PaginaHelper
end

app/views/atletas/_form.html.erb
<div class="formulario">

	<h1>Atleta</h1>

	<%= form_for(atleta) do |f| %>
		<% if atleta.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(atleta.errors.count, "error") %> prohibited this atleta from being saved:</h2>

				<ul>
				<% atleta.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
				</ul>
			</div>
		<% end %>

		<div class="field form-group">
			<%= f.label :nome %>
			<%= f.text_field :nome, class: "form-control" %>
		</div>

	 <div class="form-group">
			<%= f.label :photo %>
			<%= image_tag @atleta.photo_url, class: 'photo' if @atleta.photo? %>
			<%= f.file_field :photo, label: 'Foto' , input_html: {accept: ('application/jpg') } %>
		</div>

		<div class="field form-group">
			<%= f.label :descricao %>
			<%= f.text_field :descricao, class: "form-control" %>
		</div>

		<div class="field form-group">
			<%= f.label :modalidade_id %>
			<%= f.select :modalidade_id, Modalidade.all.map{ |u| [u.nome, u.id] }, {}, {class: "form-control"} %>
		</div>

		<div class="actions form-group">

			<%= link_to 'Back', atletas_path, class: "btn btn-default"  %>
			<%= f.submit "Registrar", :class => "btn btn-success" %>
		</div>
	<% end %>
</div>

app/views/atletas/edit.html.erb
<h1>Editing Atleta</h1>

<%= render 'form', atleta: @atleta %>

<%= link_to 'Show', @atleta %> |
<%= link_to 'Back', atletas_path %>

app/views/atletas/index.html.erb
<p id="notice"><%= notice %></p>


	<div class="page-header">
		<h1>Atletas</h1>
	</div>

<table class="table">
  <thead>
    <tr>
			<th></th>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Modalidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atletas.each do |atleta| %>
      <tr>
				<td><%= image_tag atleta.photo, class: "profile-pic mini" %></td>
        <td><%= atleta.nome %></td>
        <td><%= atleta.descricao %></td>
        <td><%= atleta.modalidade.nome %></td>
        <td>
					<%= link_to 'Mostrar', atleta %>
						
				</td>
        <td><%= link_to 'Editar', edit_atleta_path(atleta) %></td>
        <td><%= link_to 'Excluir', atleta, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Atleta', new_atleta_path, class: "btn btn-success" %>

app/views/atletas/new.html.erb
<%= render 'form', atleta: @atleta %>

app/views/atletas/show.html.erb
<div class="formulario">

	<p id="notice"><%= notice %></p>

	<div class="page-header">
		<%= image_tag @atleta.photo, class: "profile-pic middle"%>
		<h1><%= @atleta.nome %></h1>
	</div>

	<p>
		<strong>Descricao:</strong>
		<%= @atleta.descricao %>
	</p>

	<p>
		<strong>Modalidade:</strong>
		<%= @atleta.modalidade.nome %>
	</p>

	<%= link_to 'Back', atletas_path, class: "btn btn-default" %>
	<%= link_to 'Edit', edit_atleta_path(@atleta), class: "btn btn-info" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Olimpiadas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<div class="navbar-header">
					<a class="navbar-brand" href="#">Olimpíadas</a>
				</div>
				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="<%= 'active' if current_page?(pagina_home_path) %>"><%= link_to "Home", pagina_home_path %></li>
					<li class="<%= 'active' if current_page?(atletas_path) %>"><%= link_to "Atletas", atletas_path  %></li>
					<li class="<%= 'active' if current_page?(modalidades_path) %>"><%= link_to "Modalidades", modalidades_path  %></li>
				</ul>
			</div>
		</nav>
	
    <%= yield %>
  </body>
</html>

app/views/modalidades/_form.html.erb
<div class="formulario">
	<h1>Modalidade</h1>
<%= form_for(modalidade) do |f| %>
  <% if modalidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(modalidade.errors.count, "error") %> prohibited this modalidade from being saved:</h2>

      <ul>
      <% modalidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :nome %>
    <%= f.text_field :nome, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :descricao %>
    <%= f.text_field :descricao, class: "form-control" %>
  </div>

  <div class="actions form-group">
		<%= link_to 'Back', modalidades_path, class: "btn btn-default" %>
    <%= f.submit "Registrar", :class => "btn btn-success" %>
  </div>
<% end %>
</div>

app/views/modalidades/edit.html.erb
<h1>Editing Modalidade</h1>

<%= render 'form', modalidade: @modalidade %>

<%= link_to 'Show', @modalidade %> |
<%= link_to 'Back', modalidades_path %>

app/views/modalidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Modalidades</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @modalidades.each do |modalidade| %>
      <tr>
        <td><%= modalidade.nome %></td>
        <td><%= modalidade.descricao %></td>
        <td><%= link_to 'Mostrar', modalidade %></td>
        <td><%= link_to 'Editar', edit_modalidade_path(modalidade) %></td>
        <td><%= link_to 'Excluir', modalidade, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Modalidade', new_modalidade_path, class: "btn btn-success" %>

app/views/modalidades/new.html.erb
<%= render 'form', modalidade: @modalidade %>

app/views/modalidades/show.html.erb
<div class="formulario">

	<p id="notice"><%= notice %></p>
	
	<div class="page-header">
		<h1><%= @modalidade.nome %></h1>
	</div>
	<p>
		<%= @modalidade.descricao %>
	</p>
	
	<%= link_to 'Back', modalidades_path, class: "btn btn-default" %>
	<%= link_to 'Edit', edit_modalidade_path(@modalidade), class: "btn btn-info" %>

</div>

app/views/pagina/home.html.erb
<div class="home">
	<h1 class="home">Bem Vindo!!!</h1>
	<p class="home">
		Aqui você pode encontrar informações sobre Atletas e Modalidades das Olimpíadas Rio 2016!
	</p>
	<%= link_to "Novo Atleta", new_atleta_path, class: "btn btn-primary" %>
	<%= link_to "Nova Modalidade", new_modalidade_path, class: "btn btn-success" %>
</div>